### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by 0xNazarii**

### CODE REVIEW

**Review by andrieieva-yuliia — APPROVED** [review]
Nice work 🤩

**Review by alexandra-protyanova — APPROVED** [review]

**Comment by OlyaZaiets** [comment]
nice

**Comment by OlyaZaiets** [comment]
nice

**Review by OlyaZaiets — APPROVED** [review]
nice

**Comment by nzrii-kysel** [comment]
> nice

nice what

**Review by PolinaSukhorukova — APPROVED** [review]
GJ

**Pull request closed without merging**
